name: Diary
url: https://diary.aoirint.com
author: aoirint
permalink: /:year/:month/:day/:title/
timezone: Asia/Tokyo
theme: primer
lang: ja
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-archives
